# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f1ef450eb8f8f635366b6b070f07bc278ee072a0c8aa7c5dcf6a08a2ecb5d4cca21bb4ccb5135fb39d0a19d2c0657a640c800fdbff72abda945c70908c3bebf

test:
  secret_key_base: 4e83430c91df05b541dfc5213933aa245419b6a7b42a8a9954bf8c54cfdf974063c1771081d1e9c5b265c80a486d4fb9b9d192f7d4dac9a57250958e097cc7af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
